-- CyberOS Hyprland config -- Cyber Department theme.
-- Lua format: the .conf format is removed in Hyprland 0.57.
-- Docs: https://wiki.hypr.land/Configuring/

---------------------------------------------------------------- palette
-- Colours are generated by cyberos-theme into theme.lua and must not be
-- written here: Super+Shift+T regenerates that file and reloads. The
-- fallback below only exists so a missing theme.lua degrades to a usable
-- desktop instead of tripping Hyprland's emergency mode.
local cfgdir = (os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")) .. "/hypr"
local ok, theme = pcall(dofile, cfgdir .. "/theme.lua")
if not ok or type(theme) ~= "table" then
  theme = { accent = "rgb(00CA4E)", border = "rgb(3A3A3C)" }
end

---------------------------------------------------------------- touchscreen state
-- Restores a touchscreen disable across `hyprctl reload` (Super+Shift+R) and
-- fresh logins. cyberos-toggle-touchscreen (Super+Shift+U) writes the
-- device's own name here when disabling it; read back as a plain Lua string
-- value below, never built into code, so there is nothing for it to inject
-- even if it somehow contained Lua syntax.
local state_home = os.getenv("XDG_STATE_HOME") or (os.getenv("HOME") .. "/.local/state")
local touch_state = io.open(state_home .. "/cyberos/touchscreen-disabled-name", "r")
if touch_state then
  local name = touch_state:read("*l")
  touch_state:close()
  if name and name ~= "" then
    hl.device({ name = name, enabled = false })
  end
end

---------------------------------------------------------------- monitors
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })

-- cyberos-monitor-arrange (the Arrange bar chip) persists placement/refresh
-- rate choices in a marked block at the end of this file, applied after the
-- catch-all rule above so a per-monitor rule wins. Same guarded-dofile shape
-- as theme.lua above: pcall so a machine that has never used the panel (no
-- monitors.lua yet) degrades to the automatic layout above instead of
-- tripping Hyprland's emergency mode.
pcall(dofile, cfgdir .. "/monitors.lua")

---------------------------------------------------------------- programs
local terminal = "foot"
local browser  = "firefox"
-- dolphin is gone; Files is a Quickshell surface in the running shell.
local files    = "cyberos-files" -- wrapper: always passes an explicit arg, empty here
local editor   = "code"

---------------------------------------------------------------- autostart
hl.on("hyprland.start", function()
  hl.exec_cmd("swaybg -i /usr/share/backgrounds/cyberos/wallpaper.png -m fill")
  hl.exec_cmd("qs")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  -- Cloud Drives' config-encryption secret lives only here (secret-tool /
  -- org.freedesktop.secrets), never on disk in the clear. Started plain,
  -- not PAM-unlocked at login -- see packages.x86_64's own comment on why
  -- that tradeoff fits this project's lab-machine threat model.
  hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
end)

---------------------------------------------------------------- environment
hl.env("XCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("GDK_BACKEND", "wayland,x11")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

---------------------------------------------------------------- look and feel
hl.config({
  general = {
    gaps_in = 2,
    gaps_out = 2,
    border_size = 1,
    col = {
      active_border   = theme.accent,
      inactive_border = theme.border,
    },
    layout = "dwindle",
    resize_on_border = true,
  },

  decoration = {
    rounding = 2,
    active_opacity = 0.92,
    inactive_opacity = 0.85,
    shadow = { enabled = true, range = 12, render_power = 3, color = "rgba(00000088)" },
    blur   = { enabled = true, size = 10, passes = 3, vibrancy = 0.17 },
  },

  animations = { enabled = true },

  dwindle = { preserve_split = true },

  input = {
    kb_layout = "us",
    follow_mouse = 1,
    sensitivity = 0,
    touchpad = { natural_scroll = true, tap_to_click = true },
  },

  cursor = {
    -- VMs (VMware/VirtualBox) have broken hardware cursor planes.
    no_hardware_cursors = true,
  },

  misc = {
    disable_hyprland_logo = true,
    disable_splash_rendering = true,
    force_default_wallpaper = 0,
  },

  ecosystem = {
    -- Hyprland pops an "updated to X!" window on the first login after a
    -- version bump. Every student would meet it once on a fresh lab machine,
    -- so suppress it; release notes still live at hypr.land.
    no_update_news = true,
    no_donation_nag = true,
  },
})

hl.curve("ease", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({ leaf = "windows",    enabled = true, speed = 5, bezier = "ease",    style = "slide" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 5, bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "border",     enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "fade",       enabled = true, speed = 6, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "ease" })

---------------------------------------------------------------- keybinds
local mod = "SUPER"

hl.bind(mod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mod .. " + D",      hl.dsp.exec_cmd("qs ipc call launcher toggle"))
-- the GTK launch helper is gone with GTK; exec the installer .desktop's command directly.
hl.bind(mod .. " + I",      hl.dsp.exec_cmd('foot --app-id=cyberos-installer --title="Install CyberOS" sudo /usr/local/bin/cyberos-install'))
hl.bind(mod .. " + Tab",    hl.dsp.exec_cmd("qs ipc call winswitch toggle"))
hl.bind(mod .. " + period", hl.dsp.exec_cmd("qs ipc call emoji toggle"))
hl.bind(mod .. " + equal",  hl.dsp.exec_cmd("qs ipc call calc toggle"))
hl.bind(mod .. " + B",      hl.dsp.exec_cmd(browser))
hl.bind(mod .. " + E",      hl.dsp.exec_cmd(files))
hl.bind(mod .. " + C",      hl.dsp.exec_cmd(editor))
hl.bind(mod .. " + Q",      hl.dsp.window.close())
hl.bind(mod .. " + F",      hl.dsp.window.fullscreen({ action = "toggle", mode = "fullscreen" }))
hl.bind(mod .. " + V",      hl.dsp.window.float({ action = "toggle" }))
hl.bind(mod .. " + P",      hl.dsp.window.pseudo())
hl.bind(mod .. " + S",      hl.dsp.layout("togglesplit"))
hl.bind(mod .. " + Escape", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mod .. " + SHIFT + E", hl.dsp.exit())
hl.bind(mod .. " + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload"))
hl.bind(mod .. " + SHIFT + T", hl.dsp.exec_cmd("cyberos-theme toggle"))
-- No natural free letter (T is theme); U picked arbitrarily and documented
-- here, since there is no hardware key for this the way volume/brightness
-- have XF86 keys.
hl.bind(mod .. " + SHIFT + U", hl.dsp.exec_cmd("cyberos-toggle-touchscreen"))
hl.bind(mod .. " + X", hl.dsp.exec_cmd("qs ipc call clip toggle"))

-- screenshots
hl.bind("Print",         hl.dsp.exec_cmd('grim -g "$(slurp)" - | wl-copy'))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("grim ~/Pictures/screenshot-$(date +%Y%m%d-%H%M%S).png"))

-- focus / move: vim keys and arrows
local dirs = { H = "left", L = "right", K = "up", J = "down",
               left = "left", right = "right", up = "up", down = "down" }
for key, direction in pairs(dirs) do
  hl.bind(mod .. " + " .. key,             hl.dsp.focus({ direction = direction }))
  hl.bind(mod .. " + SHIFT + " .. key,     hl.dsp.window.move({ direction = direction }))
end

-- workspaces 1-10 on the number row
for i = 1, 10 do
  local key = i % 10
  hl.bind(mod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
  hl.bind(mod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end
hl.bind(mod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- media / brightness (locked: work on the lock screen; repeating: hold to keep going)
-- swayosd is gone -- these dispatch into the Quickshell OSD's ipc target.
hl.bind("XF86AudioRaiseVolume",  hl.dsp.exec_cmd("qs ipc call osd volumeUp"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume",  hl.dsp.exec_cmd("qs ipc call osd volumeDown"), { locked = true, repeating = true })
hl.bind("XF86AudioMute",         hl.dsp.exec_cmd("qs ipc call osd volumeMute"), { locked = true })
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("qs ipc call osd brightnessUp"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("qs ipc call osd brightnessDown"), { locked = true, repeating = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

---------------------------------------------------------------- window rules
hl.window_rule({ name = "float-installer", match = { class = "^(cyberos-installer)$" }, float = true, size = { 920, 640 }, center = true })
hl.window_rule({ name = "float-cloud-drives", match = { class = "^(cyberos-cloud-drives)$" }, float = true, size = { 720, 420 }, center = true })
hl.window_rule({ name = "float-pip",  match = { title = "^(Picture-in-Picture)$" }, float = true })
hl.window_rule({ name = "float-vbox", match = { class = "^(VirtualBox Machine)$" }, float = true })
hl.window_rule({ name = "suppress-maximize", match = { class = ".*" }, suppress_event = "maximize" })

-- blur the floating bar/launcher/OSD/power-menu/window-switcher/emoji-picker/
-- calculator/clipboard-history (all Quickshell surfaces share the
-- "quickshell" layer namespace -- drun, window, emoji, calc and clipboard
-- are all quickshell now, rofi is gone).
hl.layer_rule({ match = { namespace = "quickshell" }, blur = true, ignore_alpha = 0.3 })
